### ISSUE TITLE
Question about loren.py

### ISSUE THREAD

**Issue by nicola1M** [jiangjiechen/LOREN#3]
Hello,

I have a question about the loren.py file.

In line: 93-94:
`results = self.sent_client.identify_NPs(deal_bracket(js['claim'], True),
                                                candidate_NPs=[x[0] for x in js['evidence']])`

Why do you use the first letter for each js['evidence'] as candidate_NPs? Should it may be: 

`results = self.sent_client.identify_NPs(deal_bracket(js['claim'], True),
                                                candidate_NPs=js['entities']])`

Thanks in advance!

**Comment by jiangjiechen** [comment]
Thank you for pointing this out! It was a careless mistake in deployment and has been corrected.
